apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31111
  selector:
    app: front