name: publish

on: [push]

jobs:
  publish-back-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to github image repo
      run: |
        echo $CR_PAT | docker login ghcr.io -u tigrohvost --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    -
        name: Build and push back
        uses: docker/build-push-action@v4
        with:
          context: ./components/back
          push: true
          tags: ghcr.io/tigrohvost/back:latest

    -
        name: Build and push front
        uses: docker/build-push-action@v4
        with:
          context: ./components/front
          push: true
          tags: ghcr.io/tigrohvost/front:latest

